// Validation batch: 10 real New England D1-D3 schools, verified live on 2026-08-04 by
// fetching each school's actual athletics schedule page and confirming SIDEARM CMS
// fingerprints (dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/... asset domains,
// "Sidearm Sports" footer attribution). See CLAUDE.md Section 8 for the platform-mix finding.
export const SCHOOLS_SEED = [
  {
    name: "Amherst College",
    conference: "NESCAC",
    division: "D3",
    city: "Amherst",
    state: "MA",
    lat: 42.3709,
    lng: -72.5148,
    websiteUrl: "https://athletics.amherst.edu",
    cmsPlatform: "sidearm",
  },
  {
    name: "Williams College",
    conference: "NESCAC",
    division: "D3",
    city: "Williamstown",
    state: "MA",
    lat: 42.7128,
    lng: -73.2032,
    websiteUrl: "https://ephsports.williams.edu",
    cmsPlatform: "sidearm",
  },
  {
    name: "Bowdoin College",
    conference: "NESCAC",
    division: "D3",
    city: "Brunswick",
    state: "ME",
    lat: 43.9128,
    lng: -69.9653,
    websiteUrl: "https://athletics.bowdoin.edu",
    cmsPlatform: "sidearm",
  },
  {
    name: "Middlebury College",
    conference: "NESCAC",
    division: "D3",
    city: "Middlebury",
    state: "VT",
    lat: 44.0134,
    lng: -73.167,
    websiteUrl: "https://athletics.middlebury.edu",
    cmsPlatform: "sidearm",
  },
  {
    name: "Tufts University",
    conference: "NESCAC",
    division: "D3",
    city: "Medford",
    state: "MA",
    lat: 42.4085,
    lng: -71.118,
    websiteUrl: "https://gotuftsjumbos.com",
    cmsPlatform: "sidearm",
  },
  {
    name: "Bentley University",
    conference: "Northeast-10",
    division: "D2",
    city: "Waltham",
    state: "MA",
    lat: 42.3868,
    lng: -71.2359,
    websiteUrl: "https://bentleyfalcons.com",
    cmsPlatform: "sidearm",
  },
  {
    name: "Saint Anselm College",
    conference: "Northeast-10",
    division: "D2",
    city: "Goffstown",
    state: "NH",
    lat: 43.009,
    lng: -71.6086,
    websiteUrl: "https://saintanselmhawks.com",
    cmsPlatform: "sidearm",
  },
  {
    name: "Assumption University",
    conference: "Northeast-10",
    division: "D2",
    city: "Worcester",
    state: "MA",
    lat: 42.2896,
    lng: -71.7987,
    websiteUrl: "https://assumptiongreyhounds.com",
    cmsPlatform: "sidearm",
  },
  {
    name: "University of Vermont",
    conference: "America East",
    division: "D1",
    city: "Burlington",
    state: "VT",
    lat: 44.4759,
    lng: -73.1959,
    websiteUrl: "https://uvmathletics.com",
    cmsPlatform: "sidearm",
  },
  {
    name: "Bryant University",
    conference: "America East",
    division: "D1",
    city: "Smithfield",
    state: "RI",
    lat: 41.9226,
    lng: -71.5495,
    websiteUrl: "https://bryantbulldogs.com",
    cmsPlatform: "sidearm",
  },
] as const;
