export const SPORTS_SEED = [
  { name: "football", typicalSeason: "fall" },
  { name: "soccer", typicalSeason: "fall" },
  { name: "field hockey", typicalSeason: "fall" },
  { name: "volleyball", typicalSeason: "fall" },
  { name: "cross country", typicalSeason: "fall" },
  { name: "sailing", typicalSeason: "fall" },
  { name: "basketball", typicalSeason: "winter" },
  { name: "ice hockey", typicalSeason: "winter" },
  { name: "squash", typicalSeason: "winter" },
  { name: "swimming and diving", typicalSeason: "winter" },
  { name: "wrestling", typicalSeason: "winter" },
  { name: "indoor track and field", typicalSeason: "winter" },
  { name: "lacrosse", typicalSeason: "spring" },
  { name: "baseball", typicalSeason: "spring" },
  { name: "softball", typicalSeason: "spring" },
  { name: "rowing", typicalSeason: "spring" },
  { name: "outdoor track and field", typicalSeason: "spring" },
  { name: "tennis", typicalSeason: "spring" },
  { name: "golf", typicalSeason: "spring" },
] as const;
